# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
---
version: '3.7'

services:

  spdk:
    # image: ghcr.io/opiproject/spdk:v24.01
    build:
      context: .
    volumes:
      - /dev/hugepages:/dev/hugepages
      - /dev/shm:/dev/shm
      - /proc:/proc
      - /var/tmp:/var/tmp
      - /dev/zvol:/dev/zvol
      - /home/wf/spdk:/home/wf/spdk
    privileged: true
    network_mode: host
    working_dir: /usr/libexec/spdk/scripts
    command: |
      sh -x -c '/usr/local/bin/spdk_tgt -m 0x1 -c /home/wf/spdk/rdma_config.json -S /var/tmp'
    healthcheck:
      test: ["CMD-SHELL", "python3 /usr/libexec/spdk/scripts/rpc.py spdk_get_version || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s
    restart: always